Bootstrap: docker
From: ubuntu:xenial

%help
### This is the help for building a singularity image from a recipe (sudo priveleges required).
### To build me into an image, run:
    sudo singularity build my-new-SneakerNet-image.simg /path/to/SneakerNet/Singularity
### If the image already exists, add the --force flag to overwrite
    sudo singularity build --force my-new-SneakerNet-image.simg /path/to/SneakerNet/Singularity

#### Then to run in an interactive shell run:
    singularity shell my-new-SneakerNet-image.simg
    SneakerNet.pl --help

#### To run without interactive shell
    singularity exec my-new-SneakerNet-image.simg SneakerNet.pl

%labels
    MAINTAINER Curtis Kapsak
    SINGULARITY-IMAGE-VERSION 1.0.0
    SOFTWARE-VERSION 0.3
    SOFTWARE-WEBSITE https://github.com/lskatz/SneakerNet/
    SOFTWARE-LICENSE https://github.com/lskatz/SneakerNet/blob/master/LICENSE

%environment
PATH=${PATH}:/mlst-2.16.2/bin:\
/skesa:\
/kraken-1.1:\
/kraken-1.1/kraken-scripts:\
/kraken-1.1/scripts:\
/CG-Pipeline-0.5/scripts:\
/data/bin/SneakerNet-0.3/scripts:\
/data/bin/SneakerNet-0.3/SneakerNet.plugins

    export PATH
    export LC_ALL=C
    export PERL5LIB=/data/lib/perl5

%files
    /home/curtis/github-repos/SneakerNet/singularity/config/* /

%post
    apt-get update
    apt-get -y install wget \
                       curl \
                       perl \
                       bioperl \
                       make \
                       build-essential \
                       cpanminus \
                       git \
                       ncbi-blast+ \
                       gzip \
                       zlib1g-dev \
                       g++ \
                       cpanminus \
                       sendmail-base \
                       glibc-source \
                       prodigal

    # install CG-pipeline
    wget https://github.com/lskatz/CG-Pipeline/archive/v0.5.tar.gz
    tar -xzf v0.5.tar.gz
    rm v0.5.tar.gz

    # install Krona
    wget https://github.com/marbl/Krona/releases/download/v2.7.1/KronaTools-2.7.1.tar
    tar -xf KronaTools-2.7.1.tar
    rm KronaTools-2.7.1.tar
    cd KronaTools-2.7.1
    ./install.pl --prefix .
    ./updateTaxonomy.sh

    # install Jellyfish (kraken dep.)
    cd /
    wget https://github.com/gmarcais/Jellyfish/releases/download/v1.1.12/jellyfish-1.1.12.tar.gz
    tar -zxf jellyfish-1.1.12.tar.gz
    rm -rf jellyfish-1.1.12.tar.gz
    cd jellyfish-1.1.12
    ./configure --prefix=/opt/
    make -j 4
    make install

    # kraken install
    cd /
    wget https://github.com/DerrickWood/kraken/archive/v1.1.tar.gz
    tar -xzf v1.1.tar.gz
    rm -r v1.1.tar.gz
    cd kraken-1.1
    mkdir kraken-scripts
    ./install_kraken.sh kraken-scripts/

    # DL minikraken DB
    mkdir /kraken-database
    cd /kraken-database
    ##temorary commenting out to speed up build process
#    wget https://ccb.jhu.edu/software/kraken/dl/minikraken_20171019_4GB.tgz
 #   tar -xzf minikraken_20171019_4GB.tgz
  #  rm minikraken_20171019_4GB.tgz

    # install skesa (pre-compiled binary)
    mkdir /skesa
    cd /skesa
    wget https://github.com/ncbi/SKESA/releases/download/v2.3.0/skesa.centos6.10
    mv skesa.centos6.10 skesa
    chmod +x skesa

    # install MLST (Torsten's tool)
    apt-get install -y libmoo-perl liblist-moreutils-perl libjson-perl file
    cd /
    wget https://github.com/tseemann/mlst/archive/v2.16.2.tar.gz
    tar -zxf v2.16.2.tar.gz
    rm v2.16.2.tar.gz
    # make sure MLST is installed
    ./mlst-2.16.2/bin/mlst --check
    ./mlst-2.16.2/bin/mlst --list

    # get SneakerNet files, put in /data/bin
    mkdir /data
    mkdir /data/bin
    cd /data/bin
    wget https://github.com/lskatz/SneakerNet/archive/v0.3.tar.gz
    tar -xzf v0.3.tar.gz
    rm v0.3.tar.gz

    # install perl modules
    cpanm --local-lib=/data/lib/perl5 local::lib && eval $(perl -I /data/perl5/lib/perl5/ -Mlocal::lib)
    cpanm -l /data --force Test::Most \
                  Bio::FeatureIO \
                  String::Escape \
                  File::Slurp \
                  URI::Escape \
                  Bio::Kmer \
                  Config::Simple \
                  Email::Stuffer \
                  Text::Fuzzy
    export PERL5LIB=/data/lib/perl5

    # install SneakerNet
    cd /data/bin/SneakerNet-0.3
    perl Makefile.PL
    make

    # set up inbox and repository directory; move config files
    mkdir /data/sn-inbox
    mkdir /data/sn-repository-dir
    mkdir /data/bin/SneakerNet-0.3/config
    mv /*.conf /data/bin/SneakerNet-0.3/config
    chmod -R a+rw /data

%runscript
    echo "This runscript shows SneakerNet help options"
    SneakerNet.pl --help
    echo ""
    echo ""
    echo ""
    echo 'Run "singularity help name-of-SneakerNet-image.simg" for more help on running the image'
    echo ""
